[files]
extend-exclude = [
    ".gitignore",
    "LICENSE",
    "legacy",
    "*.csv"
]
ignore-hidden = true
ignore-dot = true

[default]
locale = "en-gb"
extend-ignore-re = [
    # Ignore lines that end with `# spellchecker:disable-line`
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    # Ignore lines with HTML `<!-- spellchecker:disable-line -->`
    "(?Rm)^.*<!--\\s*spellchecker:disable-line\\s*-->.*$",
    # Ignore the line after `# spellchecker:ignore-next-line`:
    "(#|//)\\s*spellchecker:ignore-next-line\\n.*",
    # Ignore blocks between `# spellchecker:off` and `# spellchecker:on`
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]
